name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          flags: smart-tests
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jack-kj/study-ts
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    